version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: ./.docker/backend/
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=172.45.101.12
      - DB_DATABASE=stockpress
      - DB_USERNAME=root
      - DB_PASSWORD=stockpress123
    networks:
      stockpress_network:
        ipv4_address: 172.45.101.10

  frontend:
    restart: unless-stopped
    build:
      context: ./.docker/frontend/
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://172.45.101.10/api/
    networks:
      stockpress_network:
        ipv4_address: 172.45.101.11

  mysql:
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_DATABASE=stockpress
      - MYSQL_USER=stockpress
      - MYSQL_PASSWORD=stockpress123
      - MYSQL_ROOT_PASSWORD=stockpress123
    networks:
      stockpress_network:
        ipv4_address: 172.45.101.12

networks:
  stockpress_network:
    ipam:
      driver: default
      config:
        - subnet: "172.45.101.0/24"

